installing mysql

diff --git a/shell-script/10-installationofsql b/shell-script/10-installationofsql
--- a/shell-script/10-installationofsql
+++ b/shell-script/10-installationofsql
@@ -9,3 +9,9 @@ echo " your are super user "
 fi
 
 dnf install mysql -y
+if [ $? -ne 0]
+then
+echo "failure"
+else
+echo "success"
+fi
